app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

Route::get('medicos', ['as' => 'medicos.index', 'uses' => 'MedicoController@index']);
Route::get('medicos/create', ['as' => 'medicos.create', 'uses' => 'MedicoController@create']);
Route::post('medicos', ['as' => 'medicos.save', 'uses' => 'MedicoController@save']);
Route::get('medicos/{id}/edit', ['as' => 'medicos.edit', 'uses' => 'MedicoController@edit']);
Route::put('medicos/{id}', ['as' => 'medicos.update', 'uses' => 'MedicoController@update']);
Route::delete('medicos/{id}', ['as' => 'medicos.destroy', 'uses' => 'MedicoController@destroy']);
Route::get('medicos/pdf', ['as' => 'medicos.pdf', 'uses' => 'MedicoController@pdf']);


//buscas
Route::get('medicos/busca/', ['as' => 'medicos.busca', 'uses' => 'MedicoController@busca']);
Route::get('pacientes/busca/', ['as' => 'pacientes.busca', 'uses' => 'PacienteController@busca']);
Route::get('pacientes/busca-ajax', ['as' => 'pacientes.buscaAjax', 'uses' => 'PacienteController@buscaAjax']);


//tcles
Route::get('tcles/busca/', ['as' => 'tcles.busca', 'uses' => 'TCLEController@busca']);

//estados
Route::get('estados', function(){
    return \App\Estado::all(['id', 'nome', 'sigla']);
});

//resources controllers

Route::resource('pacientes', 'PacienteController');
Route::resource('tcles', 'TCLEController');



//jasper reports
Route::get('/reporting', ['uses' =>'ReportController@index', 'as' => 'Report']);
Route::post('/reporting', ['uses' =>'ReportController@post']);



//angular test
Route::get('lista-pacientes', 'HomeController@listaPacientes');

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>@yield('title')</title>

	<link href="/css/app.css" rel="stylesheet">

    <link rel="stylesheet" href="http://getbootstrap.com/dist/css/bootstrap.min.css">

	<!-- Fonts -->
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

    <!--includ angular -->
    <script src="/bower_components/angular/angular.js"></script>

</head>
<body>

	@include('partials.navbar')

    @include('partials.confirm-delete-dialog')


    <div class="container">
        @include('flash::message')
    </div>

	@yield('content')

	<!-- Scripts -->
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>

<script>
    $(document).ready(function(){
        function fnOpenNormalDialog() {
            $("#dialog-confirm").html("Deseja realmente excluir?");

            // Define the Dialog and its properties.
            $("#dialog-confirm").dialog({
                resizable: false,
                modal: true,
                title: "Confirmar",
                height: 250,
                width: 400,
                buttons: {
                    "Sim": function () {
                        $(this).dialog('close');
                        $('#form-delete').submit();
                    },
                    "Não": function () {
                        $(this).dialog('close');
                        return false;
                    }
                }
            });
        }

        $('.confirm-delete').click(fnOpenNormalDialog);

    });

</script>
</body>
</html>

resources/views/home.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-heading panel-title text-center">Links úteis</div>

				<div class="panel-body">
                    <ul class="list-group">
                        <a href="{{route('tcles.index')}}"><li class="list-group-item">TCLE - Anestesia final</li></a>
                        <a href="{{route('tcles.index')}}"><li class="list-group-item">TCLE - Cirurgia final</li></a>
                        <a href="{{route('tcles.index')}}"><li class="list-group-item">TCLE - Transfusão final</li></a>

                    </ul>
                </div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/lista-pacientes.blade.php
@extends('app')

@section('content')

    <!--<script src="/js/angular/carrega-paciente.js"></script>-->

    <script>
        var app = angular.module('myApp', []).config(function($interpolateProvider){
            $interpolateProvider.startSymbol('<%').endSymbol('%>');
        });

        app.controller('pacienteController', function($scope, $http){

            $scope.paciente = null;
            $scope.prontuario = null;
            $scope.mensagem = null;

            $scope.carregaPaciente = function() {
                $http.get("pacientes/busca-ajax?prontuario=" + $scope.prontuario).success(function ($response) {

                    $scope.paciente = $response.paciente;

                    if($response.paciente != null){
                        $scope.mensagem = "Nenhum paciente encontrado";
                    }

                    console.log($scope.paciente);

                });
            }
        });

    </script>

    <div ng-app="myApp" ng-controller="pacienteController">


        <input type="search" ng-model="prontuario"/>
        <button ng-click="carregaPaciente()">Pesquisar</button>


    </div>

    <table>
        <tr>
            <th>Nome</th>
            <td><% paciente.nome %></td>
        </tr>
    </table>

@endsection