app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

Route::get('medicos', ['as' => 'medicos.index', 'uses' => 'MedicoController@index']);
Route::get('medicos/create', ['as' => 'medicos.create', 'uses' => 'MedicoController@create']);
Route::post('medicos', ['as' => 'medicos.save', 'uses' => 'MedicoController@save']);
Route::get('medicos/{id}/edit', ['as' => 'medicos.edit', 'uses' => 'MedicoController@edit']);
Route::put('medicos/{id}', ['as' => 'medicos.update', 'uses' => 'MedicoController@update']);
Route::delete('medicos/{id}', ['as' => 'medicos.destroy', 'uses' => 'MedicoController@destroy']);
Route::get('medicos/pdf', ['as' => 'medicos.pdf', 'uses' => 'MedicoController@pdf']);


//buscas
Route::get('medicos/busca/', ['as' => 'medicos.busca', 'uses' => 'MedicoController@busca']);
Route::get('pacientes/busca/', ['as' => 'pacientes.busca', 'uses' => 'PacienteController@busca']);
Route::get('pacientes/busca-ajax', ['as' => 'pacientes.buscaAjax', 'uses' => 'PacienteController@buscaAjax']);


//tcles
Route::get('tcles/busca/', ['as' => 'tcles.busca', 'uses' => 'TCLEController@busca']);

//estados
Route::get('estados', function(){
    return \App\Estado::all(['id', 'nome', 'sigla']);
});

//resources controllers

Route::resource('pacientes', 'PacienteController');
Route::resource('tcles', 'TCLEController');



//jasper reports
Route::get('/reporting', ['uses' =>'ReportController@index', 'as' => 'Report']);
Route::post('/reporting', ['uses' =>'ReportController@post']);



//angular test
Route::get('lista-pacientes', 'HomeController@listaPacientes');

app/TCLE.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class TCLE extends Model {

	protected $table = 'tcles';

    protected $dates = ['data_nascimento'];

    protected $fillable = ['diagnostico', 'procedimento', 'anestesia',
    'responsavel', 'parentesco_responsavel', 'rg_responsavel', 'cpf_responsavel', 'user_id', 'estados_id', 'paciente_id'];

    public function estado(){

        return $this->hasOne('App\Estado', 'id', 'estados_id');
    }

    public function paciente()
    {
        return $this->hasOne('App\Paciente', 'id', 'paciente_id'); 
    }

}

app/Http/Controllers/TCLEController.php
<?php namespace App\Http\Controllers;

use App\Estado;
use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Services\TCLEService;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Laracasts\Flash\Flash;

class TCLEController extends Controller {

    private $service;

    public function __construct(TCLEService $service){
        $this->service = $service;
        $this->middleware('auth');
    }

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{

        $user_id = Auth::user()->id;

        $tcles = $this->service->findAllByUserId($user_id);

        return view('tcles.index')->with('tcles', $tcles)->with('paginado', true);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{

        //$estados = Estado::all(['id', 'nome', 'sigla'])->orderBy('sigla', 'asc')->get();

        $estados = DB::table('estados')->select(['id', 'sigla'])->orderBy('sigla', 'asc')->get();

		return view('tcles.create')->with('estados', $estados);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(Requests\TCLERequest $request)
	{
		$this->service->save($request->all());

        Flash::success("Novo registro inserido!");

        return redirect()->route('tcles.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$tcle = $this->service->findById($id);


        return view('tcles.show')->with('tcle', $tcle);

	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
        //
        $tcle = $this->service->findById($id);

        //
        $estadosList = DB::table('estados')->select(['id', 'sigla'])->orderBy('sigla', 'asc')->get();

        $estados = array();

        foreach($estadosList as $e){
            $estados[$e->id] = $e->sigla;
        }


        return view('tcles.edit')->with('tcle', $tcle)->with('estados', $estados);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(Requests\TCLERequest $request, $id)
	{
		$tcle = $this->service->findById($id);

        $data = $request->all();

        //formatando a data.
        $data['data_nascimento'] = Carbon::createFromFormat('d/m/Y', $data['data_nascimento']);

        $tcle->update($data, $id);

        Flash::warning("Registro atualizado!");

        return redirect()->route('tcles.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$this->service->delete($id);

        Flash::error("Registro excluido!");

        return redirect()->route('tcles.index');
	}


    public function busca(Request $request){
        $paciente = null;
        if($request->has('paciente')){
            $paciente = $request->get('paciente');
        }

        $tcles = $this->service->findByNome($paciente);

        return view('tcles.index')->with('tcles', $tcles)->with('paginado', false);
    }

}

resources/views/tcles/create.blade.php
@extends('app')

@section('title')
    Adicionar novo registro
@endsection

@section('content')

    <script>
        var app = angular.module('myApp', []).config(function($interpolateProvider){
            $interpolateProvider.startSymbol('<%').endSymbol('%>');
        });

        app.controller('pacienteController', function($scope, $http){

            $scope.paciente = null;
            $scope.prontuario = null;
            $scope.mensagem = null;

            $scope.carregaPaciente = function() {
                $http.get("pacientes/busca-ajax?prontuario=" + $scope.prontuario).success(function ($response) {

                    $scope.paciente = $response.paciente;

                    if($response.paciente != null){
                        $scope.mensagem = "Nenhum paciente encontrado";
                    }

                    console.log($scope.paciente);

                });
            }
        });

    </script>

    <div class="container">

        <div class="page-header">
            <h4>Adicionar novo tcle de anestesia</h4>
        </div>

        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">

                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Opa!</strong> Existe algum problema com os valores informados.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <form class="form-horizontal" role="form" method="POST" action="{{route('tcles.store')}}">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <input type="hidden" name="user_id" value="{{Auth::user()->id}}"/>



                    <hr/>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Diagnóstico</label>
                        <div class="col-md-6">
                            <textarea class="form-control" name="diagnostico"></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Procedimento</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="procedimento">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Anestesia</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="anestesia">
                        </div>
                    </div>

                    <hr/>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Responsável</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="responsavel">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Parentesco</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="parentesco_responsavel">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">RG do responsável</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="rg_responsavel">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">CPF do responsável</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="cpf_responsavel">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-4">
                            <button type="submit" class="btn btn-primary">
                                <i class="glyphicon glyphicon-ok"></i> Adicionar
                            </button>
                            <button type="reset" class="btn btn-warning">
                                <i class="glyphicon glyphicon-refresh"></i> Limpar
                            </button>
                            <a href="{{route('tcles.index')}}" class="btn btn-danger"><i class="glyphicon glyphicon-backward"></i> Voltar </a>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
@endsection

resources/views/tcles/edit.blade.php
@extends('app')

@section('title')
    Editando registro
@endsection

@section('content')
    <div class="container">

        <div class="page-header">
            <h4>Editando registro</h4>
        </div>

        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">

                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Opa!</strong> Existe algum problema com os valores informados.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <form class="form-horizontal" role="form" method="POST" action="{{route('tcles.update', ['id' => $tcle->id])}}">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <input type="hidden" name="_method" value="PUT"/>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Paciente</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="paciente" value="{{$tcle->paciente}}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Prontuário</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="prontuario" value="{{$tcle->prontuario}}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Data de nascimento</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="data_nascimento" value="{{date('d/m/Y', strtotime($tcle->data_nascimento))}}">
                        </div>
                    </div>

                    <hr/>

                    <div class="form-group">
                        <label class="col-md-4 control-label">RG</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="rg" value="{{$tcle->rg}}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Orgão</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="orgao" value="{{$tcle->orgao}}">
                        </div>
                    </div>

                    <!--
                    <div class="form-group">
                        <label class="col-md-4 control-label">UF</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="uf" value="{{$tcle->uf}}">
                        </div>
                    </div>
                    -->

                    <div class="form-group">
                        {!! Form::label('estado_id', 'UF', ['class' => ' col-md-4 control-label']) !!}
                        <div class="col-md-6">
                            {!! Form::select('estados_id', $estados, $tcle->estados_id, ['class' => 'form-control']) !!}
                        </div>
                    </div>

                    <hr/>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Diagnóstico</label>
                        <div class="col-md-6">
                            <textarea class="form-control" name="diagnostico">{{$tcle->diagnostico}}</textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Procedimento</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="procedimento" value="{{$tcle->procedimento}}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Anestesia</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="anestesia" value="{{$tcle->anestesia}}">
                        </div>
                    </div>

                    <hr/>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Responsável</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="responsavel" value="{{$tcle->responsavel}}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Parentesco</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="parentesco_responsavel" value="{{$tcle->parentesco_responsavel}}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">RG do responsável</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="rg_responsavel" value="{{$tcle->rg_responsavel}}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">CPF do responsável</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="cpf_responsavel" value="{{$tcle->cpf_responsavel}}">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-4">
                            <button type="submit" class="btn btn-primary">
                                <i class="glyphicon glyphicon-ok"></i> Salvar
                            </button>
                            <a href="{{route('tcles.index')}}" class="btn btn-warning"><i class="glyphicon glyphicon-backward"></i> Voltar </a>
                        </div>
                    </div>
                </form>

                    {!! Form::model($tcle, ['route' => ['tcles.destroy', $tcle->id], 'id' => 'form-delete', 'method' => 'DELETE']) !!}

                        <button type="button" class="btn btn-danger confirm-delete">
                            <i class="glyphicon glyphicon-remove"></i> Excluir
                        </button>

                    {!! Form::close() !!}

                <div class="page-header">

                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/tcles/index.blade.php
@extends('app')

@section('title')
    Lista de registros
@stop

@section('content')
    <div class="container">

        <div class="page-header">
            <h4>Lista de registros</h4>
        </div>


        <div class="row">
            <div class="col-lg-6 col-lg-offset-3">

                <span class="pull-right"> <a href="{{route('tcles.create')}}" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span> Novo</a></span>

                <form action="{{route('tcles.busca')}}" method="get" class="form-inline">
                    <div class="form-group">
                        <label for="paciente" class="control-label">Nome</label>
                        <input type="text" name="paciente" id="paciente" class="form-control" required=""/>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Buscar" class="form-control btn-primary"/>
                    </div>
                </form>

                <br/><br/>

                <table class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Paciente</th>
                            <th>Prontuário</th>
                            <th>RG</th>
                            <th>Editar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($tcles as $registro)
                            <tr>
                                <td><a href="{{route('tcles.show', ['id' => $registro->id])}}">{{$registro->paciente}}</a></td>
                                <td>{{$registro->prontuario}}</td>
                                <td>{{$registro->rg}}</td>
                                <td><a href="{{route('tcles.edit', ['id' => $registro->id])}}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span> editar</a> </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

                @unless($paginado == false)
                {!! $tcles->render() !!}
                @endunless
            </div>
        </div>
    </div>
@stop

resources/views/tcles/show.blade.php
@extends('app')

@section('title')
   Informações de {{$tcle->paciente}}
@endsection

@section('content')

    <div class="container">

        <div class="row">

            <!--Informações do paciente-->

            <div class="col-lg-6">
                <div class="panel panel-primary">
                    <div class="panel-heading panel-title text-center">Informações gerais</div>

                    <div class="panel-body">

                        <div class="row">

                            <!--Informações do paciente-->
                            <div class="col-lg-6">
                                <div class="panel panel-default">
                                    <div class="panel-heading panel-title text-center">Paciente</div>

                                    <div class="panel-body">

                                        <table class="table">
                                            <tr>
                                                <th>Paciente</th>
                                                <td>{{$tcle->paciente}}</td>
                                            </tr>
                                            <tr>
                                                <th>Data de nascimento</th>
                                                <td>{{date('d/m/Y', strtotime($tcle->data_nascimento))}}</td>
                                            </tr>
                                            <tr>
                                                <th>RG</th>
                                                <td>{{$tcle->rg}}</td>
                                            </tr>
                                            <tr>
                                                <th>Orgão</th>
                                                <td>{{$tcle->orgao}}</td>
                                            </tr>
                                            <tr>
                                                <th>UF</th>
                                                <td>{{$tcle->estado->sigla}}</td>
                                            </tr>
                                        </table>

                                    </div>
                                </div>
                            </div>

                            <!-- Informações do parente -->
                            <div class="col-lg-6">
                                <div class="panel panel-default">
                                    <div class="panel-heading panel-title text-center">Parente/Responsável</div>

                                    <div class="panel-body">

                                        <table class="table">
                                            <tr>
                                                <th>Responsável</th>
                                                <td>{{$tcle->responsavel}}</td>
                                            </tr>
                                            <tr>
                                                <th>Parentesco</th>
                                                <td>{{$tcle->parentesco_responsavel}}</td>
                                            </tr>
                                            <tr>
                                                <th>RG</th>
                                                <td>{{$tcle->rg_responsavel}}</td>
                                            </tr>
                                            <tr>
                                                <th>CPF</th>
                                                <td>{{$tcle->cpf_responsavel}}</td>
                                            </tr>
                                        </table>

                                    </div>
                                </div>
                            </div>

                        </div>

                    </div>
                </div>
            </div>

            <!-- Informações do procedimento -->
            <div class="col-lg-6">
                <div class="panel panel-primary">
                    <div class="panel-heading panel-title text-center">Informações do procedimento</div>

                    <div class="panel-body">

                        <table class="table">
                            <tr>
                                <th>Prontuário</th>
                                <td>{{$tcle->prontuario}}</td>
                            </tr>
                            <tr>
                                <th>Diagnóstico</th>
                                <td>{{$tcle->diagnostico}}</td>
                            </tr>
                            <tr>
                                <th>Procedimento</th>
                                <td>{{$tcle->procedimento}}</td>
                            </tr>
                            <tr>
                                <th>Anestesia</th>
                                <td>{{$tcle->anestesia}}</td>
                            </tr>
                        </table>

                    </div>
                </div>
            </div>

        </div>

    </div>

@endsection