app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);

Route::get('medicos', ['as' => 'medicos.index', 'uses' => 'MedicoController@index']);
Route::get('medicos/create', ['as' => 'medicos.create', 'uses' => 'MedicoController@create']);
Route::post('medicos', ['as' => 'medicos.save', 'uses' => 'MedicoController@save']);
Route::get('medicos/{id}/edit', ['as' => 'medicos.edit', 'uses' => 'MedicoController@edit']);
Route::put('medicos/{id}', ['as' => 'medicos.update', 'uses' => 'MedicoController@update']);
Route::delete('medicos/{id}', ['as' => 'medicos.destroy', 'uses' => 'MedicoController@destroy']);
Route::get('medicos/pdf', ['as' => 'medicos.pdf', 'uses' => 'MedicoController@pdf']);


//buscas
Route::get('medicos/busca/', ['as' => 'medicos.busca', 'uses' => 'MedicoController@busca']);
Route::get('pacientes/busca/', ['as' => 'pacientes.busca', 'uses' => 'PacienteController@busca']);
Route::get('pacientes/busca-ajax', ['as' => 'pacientes.buscaAjax', 'uses' => 'PacienteController@buscaAjax']);


//tcles
Route::get('tcles/busca/', ['as' => 'tcles.busca', 'uses' => 'TCLEController@busca']);

//estados
Route::get('estados', function(){
    return \App\Estado::all(['id', 'nome', 'sigla']);
});

//resources controllers

Route::resource('pacientes', 'PacienteController');
Route::resource('tcles', 'TCLEController');



//jasper reports
Route::get('/reporting', ['uses' =>'ReportController@index', 'as' => 'Report']);
Route::post('/reporting', ['uses' =>'ReportController@post']);



//angular test
Route::get('lista-pacientes', 'HomeController@listaPacientes');

app/Paciente.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;


class Paciente extends Model {

    public static function boot(){
        parent::boot();
    }

    protected $fillable = ['nome', 'prontuario', 'data_nascimento', 'rg', 'orgao', 'estado_id'];

    protected $dates = ['data_nascimento'];

    public function estado()
    {
        return $this->hasOne('App\Estado', 'id', 'estado_id');
    }

}

app/Http/Controllers/PacienteController.php
<?php namespace App\Http\Controllers;

use App\Estado;
use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Paciente;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Requests\PacienteRequest;
use Illuminate\Support\Facades\DB;
use Laracasts\Flash\Flash;

class PacienteController extends Controller {


    public function __construct(){
        $this->middleware('auth');
    }
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index(Request $request)
	{
        $pacientes = Paciente::paginate(5);

        if($request->ajax()){
            return $pacientes;
        }
        else{
            return view('pacientes.index')->with('pacientes', $pacientes)->with('paginado', true);
        }
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
        $estados = $this->estadosList();

		return view('pacientes.create')->with('estados', $estados);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(PacienteRequest $request)
	{
        Paciente::create($request->all());

        Flash::success("Novo paciente adicionado!");

        return redirect()->route('pacientes.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
        $paciente = null;
        if(!is_null($id)){
            $paciente = Paciente::find($id);

            if($paciente){
                return view('pacientes.show')->with('paciente', $paciente);
            }
            else{
                abort(404);
            }
        }
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
        $paciente = null;

        $estados = $this->estadosList();

		if(!is_null($id)){
            $paciente = Paciente::find($id);
            if($paciente){
                return view('pacientes.edit')->with('paciente', $paciente)->with('estados', $estados);
            }
            else{
                return abort(404);
            }
        }
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(Request $request, $id)
	{

        if(!is_null($id)){

            $paciente = Paciente::find($id);

            if($paciente){

                $data = $request->all();

                //formatando a data.
                $data['data_nascimento'] = Carbon::createFromFormat('d/m/Y', $data['data_nascimento']);
                $paciente->update($data, $id);

                Flash::warning("Informações do paciente atualizadas!");

                return redirect()->route('pacientes.index');
            }
            else{
                Flash::warning("O paciente pode ter sido removido antes de você realizar esta ação.");

                return redirect()->route('pacientes.index');
            }
        }
        else{
            return abort(404);
        }

	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
	    if(!is_null($id)){
            $paciente = Paciente::find($id);

            if($paciente){

                $paciente->destroy($id);

                Flash::success("Paciente removido!");

                return redirect()->route('pacientes.index');
            }
            else{
                Flash::warning("Parece que o paciente já havia sido removido!");
                return redirect()->route('pacientes.index');
            }
        }
	}


    public function busca(Request $request){
        $prontuario = null;
        if($request->has('prontuario')){
            $prontuario = $request->get('prontuario');
        }

        $paciente = Paciente::where('prontuario', '=', $prontuario)->get();

        return view('pacientes.index')->with('pacientes', $paciente)->with('paginado', false);
    }

    /*
     * Método para retonar uma busca baseada em requisição ajax.
     */
    public function buscaAjax(Request $request){

        $prontuario = null;

        if($request->has('prontuario')){
            $prontuario = $request->get('prontuario');
        }

        $paciente = Paciente::where('prontuario', '=', $prontuario)->get();

        return $paciente;

    }


    //retorna os estados preparand para formulario select.
    protected function estadosList(){
        $estadosList = DB::table('estados')->select(['id', 'sigla'])->orderBy('sigla', 'asc')->get();

        $estados = array();

        foreach($estadosList as $e){
            $estados[$e->id] = $e->sigla;
        }
        return $estados;
    }

}

resources/views/pacientes/create.blade.php
@extends('app')

@section('title')
    Adicionar novo paciente
@endsection

@section('content')
    <div class="container">

        <div class="page-header">
            <h4>Adicionar paciente</h4>
        </div>

        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">

                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Opa!</strong> Existe algum problema com os valores informados.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <form class="form-horizontal" role="form" method="POST" action="{{route('pacientes.store')}}">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">

                    <div class="form-group">
                        <label class="col-md-4 control-label">Nome</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="nome" value="{{ old('nome') }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Prontuário</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="prontuario" value="{{ old('prontuario') }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Data de nascimento</label>
                        <div class="col-md-6">
                            <input type="date" class="form-control" name="data_nascimento" value="{{old('data_nascimento')}}">
                        </div>
                    </div>

                    <hr/>

                    <div class="form-group">
                        <label class="col-md-4 control-label">RG</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="rg" value="{{old('rg')}}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Orgão</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="orgao" value="{{old('orgao')}}">
                        </div>
                    </div>

                    <div class="form-group">
                        {!! Form::label('estado_id', 'UF', ['class' => ' col-md-4 control-label']) !!}
                        <div class="col-md-6">
                            <div class="col-md-6">
                                {!! Form::select('estado_id', $estados, null, ['class' => 'form-control']) !!}
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-4">
                            <button type="submit" class="btn btn-primary">
                                <i class="glyphicon glyphicon-ok"></i> Adicionar
                            </button>
                            <button type="reset" class="btn btn-warning">
                                <i class="glyphicon glyphicon-refresh"></i> Limpar
                            </button>
                            <a href="{{route('pacientes.index')}}" class="btn btn-danger"><i class="glyphicon glyphicon-backward"></i> Voltar </a>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
@endsection

resources/views/pacientes/edit.blade.php
@extends('app')

@section('title')
    Editando paciente
@endsection

@section('content')
    <div class="container">

        <div class="page-header">
            <h4>Editando paciente</h4>
        </div>

        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">

                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Opa!</strong> Existe algum problema com os valores informados.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <form class="form-horizontal" role="form" method="POST" action="{{route('pacientes.update', ['id' => $paciente->id])}}">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <input type="hidden" name="_method" value="PUT"/>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Nome</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="paciente" value="{{$paciente->nome}}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Prontuário</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="prontuario" value="{{$paciente->prontuario}}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Data de nascimento</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="data_nascimento" value="{{date('d/m/Y', strtotime($paciente->data_nascimento))}}">
                        </div>
                    </div>

                    <hr/>

                    <div class="form-group">
                        <label class="col-md-4 control-label">RG</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="rg" value="{{$paciente->rg}}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">Orgão</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="orgao" value="{{$paciente->orgao}}">
                        </div>
                    </div>

                    <!--
                    <div class="form-group">
                        <label class="col-md-4 control-label">UF</label>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="uf" value="{{$paciente->uf}}">
                        </div>
                    </div>
                    -->

                    <div class="form-group">
                        {!! Form::label('estado_id', 'UF', ['class' => ' col-md-4 control-label']) !!}
                        <div class="col-md-6">
                            {!! Form::select('estado_id', $estados, $paciente->estado_id, ['class' => 'form-control']) !!}
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-4">
                            <button type="submit" class="btn btn-primary">
                                <i class="glyphicon glyphicon-ok"></i> Salvar
                            </button>
                            <a href="{{route('pacientes.index')}}" class="btn btn-warning"><i class="glyphicon glyphicon-backward"></i> Voltar </a>
                        </div>
                    </div>
                </form>

                    {!! Form::model($paciente, ['route' => ['pacientes.destroy', $paciente->id], 'id' => 'form-delete', 'method' => 'DELETE']) !!}

                        <button type="button" class="btn btn-danger confirm-delete">
                            <i class="glyphicon glyphicon-remove"></i> Excluir
                        </button>

                    {!! Form::close() !!}

                <div class="page-header">

                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/pacientes/index.blade.php
@extends('app')

@section('title')
    Lista de registros
@stop

@section('content')
    <div class="container">

        <div class="page-header">
            <h4>Lista de pacientes</h4>
        </div>


        <div class="row">
            <div class="col-lg-6 col-lg-offset-3">

                <span class="pull-right"> <a href="{{route('pacientes.create')}}" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span> Novo</a></span>

                <form action="{{route('pacientes.busca')}}" method="get" class="form-inline">
                    <div class="form-group">
                        <label for="paciente" class="control-label">Prontuário</label>
                        <input type="text" name="prontuario" id="prontuario" class="form-control" required=""/>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Buscar" class="form-control btn-primary"/>
                    </div>
                </form>

                <br/><br/>

                @if(!$pacientes->isEmpty())
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Paciente</th>
                            <th>Prontuário</th>
                            <th>RG</th>
                            <th>Editar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($pacientes as $paciente)
                            <tr>
                                <td>
                                    <a href="{{route('pacientes.show', ['id' => $paciente->id])}}">{{$paciente->nome}}</a>
                                </td>
                                <td>{{$paciente->prontuario}}</td>
                                <td>{{$paciente->rg}}</td>
                                <td>
                                    <a href="{{route('pacientes.edit', ['id' => $paciente->id])}}"><i class="glyphicon glyphicon-edit"></i> editar</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                @else
                    Nenhum resultado encontrado.
                @endif

                @unless($paginado == false)
                    {!! $pacientes->render() !!}
                @endunless
            </div>
        </div>
    </div>
@stop

resources/views/pacientes/show.blade.php
@extends('app')

@section('title')
   Informações de {{$paciente->nome}}
@endsection

@section('content')

    <div class="container">

        <div class="row">

            <!--Informações do paciente-->

            <div class="col-lg-6 col-lg-offset-3">
                <div class="panel panel-primary">
                    <div class="panel-heading panel-title text-center">Informações do paciente</div>

                    <div class="panel-body">
                        <table class="table table-bordered table-striped">
                            <tr>
                                <th>Nome</th>
                                <td>{{$paciente->nome}}</td>
                            </tr>
                            <tr>
                                <th>Prontuário</th>
                                <td>{{$paciente->prontuario}}</td>
                            </tr>
                            <tr>
                                <th>Data de nascimento</th>
                                <td>{{date('d/m/Y', strtotime($paciente->data_nascimento))}}</td>
                            </tr>
                            <tr>
                                <th>RG</th>
                                <td>{{$paciente->rg}}</td>
                            </tr>
                            <tr>
                                <th>Orgão emissor: </th>
                                <td>{{$paciente->orgao}}</td>
                            </tr>
                            <tr>
                                <th>UF</th>
                                <td>{{$paciente->estado->sigla}}</td>
                            </tr>
                        </table>
                    </div>
            </div>

        </div>

    </div>

@endsection